### ISSUE TITLE
로그인 전 시술 퍼널 저장, 간편로그인후 재저장

### ISSUE THREAD

**Issue by aixion1506** [WELLCOME-DEV-WORKS/forms-next-app#2]
로그인전, 시술 퍼널과 시술 추천 데이터를 '견적서 받기'버튼 클릭시 DB에 전송
 - 로그인 전에는 사용자 식별자( UUID)로 처리

로그인후, 기존 사용자 식별자로 저장된 데이터를 구글 간편 로그인으로 재저장 필요
- 이때, 기존 UUID 기반 아이디에서 구글 로그인 아이디로 변경 필요

**Comment by hobby-ha** [comment]
1. 데이터베이스를 사용하지 않고 해결하는 방법이 있다면 더 좋을것 같다고 생각됩니다. 간단한 폼 형식이면 브라우저 캐시나 state 로 저장해두었다가 불러오는 방식도 괜찮은것 같구요. 

2. 만약 입력하는 폼이 복잡하고 유저가 로그인 전에 입력할수 있는 폼이 여러개가 된다면 DB를 사용하는것이 더 바람직하다고 생각합니다. 어떤 설문을 불러올지 쿼리를 해야하는 상황이라는 가정을 한다면요. 

3. 만약 데이터베이스를 사용하는 방식을 채택한다면, userId 필드를 optional field 로 받고 나중에 uuid나 이런것으로 연결짓는방법도 가능해보입니다.

**Comment by Ralpooh887** [comment]
유저가 결과물을 확인하기 위해서 로그인을 강제할 예정이므로 브라우저 캐시에서 state로 저장해 두는 형식으로 진행하는것이 바람직해 보입니다. 

기존에 의견나눴던 로그인하지 않은 유저의 입력정보를 저장해야하는지에 대한 내용은, DB에 과도하게 쓰래기정보가 들어올수 있을것같습니다. 그리고 로그인을 하지 않으면 추가적인 세일즈를 할 수 있는 방안이 없으므로 사실상 없어도 되는 데이터로 생각되어 해당정보는 DB에 저장하지 않고 유저브라우저 로컬스토리지에서 유지하는 방향으로 진행하는것이 올바른 방향으로 보입니다.

세일즈에 사용될수 있는 정보가 수집되었을때에만 DB에 저장되는 형태로 개발 진행요청드립니다.

@taemin410 @aixion1506 @nayounghye

**Comment by aixion1506** [comment]
네 그러면 유저가 견적서 받기전에 LocalStorage에 한번 저장하고, 로그인 후 LocalStorage에 있는 데이터로 저장하는 식으로 하는 식으로 진행하겠습니다.
